colors:
  andalucia: ''
  aragon: ''
  asturias: '🟦🟨'
  canarias: ''
  cantabria: ''
  castilla_la_mancha: ''
  castilla_y_leon: '🟥⬜'
  cataluna: ''
  ceuta: ''
  comunidad_valenciana: ''
  extremadura: ''
  galicia: ''
  islas_baleares: ''
  la_rioja: ''
  madrid: ''
  melilla: ''
  navarra: ''
  pais_vasco: '🟩🟥'
  region_de_murcia: ''
