colors:
  asturias: '🟦'
  castilla_y_leon: '🟩'
  galicia: '🟨'
  cantabria: '🟥'
  pais_vasco: '🟪'
  navarra: '🟧'
  aragon: '🟫'
  cataluna: '⬛'
  comunidad_valenciana: '⬜'
  La_rioja: '🟥'
  Extremadura: '⬛'
